// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMerchantsAPI = "merchants_api"

// MerchantsAPI mapped from table <merchants_api>
type MerchantsAPI struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MID         int64          `gorm:"column:m_id;not null" json:"m_id"`
	Apikey      string         `gorm:"column:apikey;not null;comment:Token" json:"apikey"`             // Token
	CallbackURL string         `gorm:"column:callback_url;not null;comment:回调url" json:"callback_url"` // 回调url
	SecretKey   string         `gorm:"column:secret_key;not null;comment:回调加密参数" json:"secret_key"`    // 回调加密参数
	Remark      string         `gorm:"column:remark;comment:备注" json:"remark"`                         // 备注
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName MerchantsAPI's table name
func (*MerchantsAPI) TableName() string {
	return TableNameMerchantsAPI
}
