// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MID          int64          `gorm:"column:m_id;not null" json:"m_id"`
	No           string         `gorm:"column:no;not null;comment:订单no" json:"no"`                // 订单no
	CNo          string         `gorm:"column:c_no;not null;comment:用户no" json:"c_no"`            // 用户no
	Amount       string         `gorm:"column:amount;not null;comment:价格" json:"amount"`          // 价格
	Coin         string         `gorm:"column:coin;not null;comment:数字币类型" json:"coin"`           // 数字币类型
	Chain        string         `gorm:"column:chain;not null;comment:链" json:"chain"`             // 链
	NotifyURL    string         `gorm:"column:notify_url;comment:回调url" json:"notify_url"`        // 回调url
	ReturnURL    string         `gorm:"column:return_url;comment:前端重定向url" json:"return_url"`     // 前端重定向url
	PayURL       string         `gorm:"column:pay_url;comment:支付地址" json:"pay_url"`               // 支付地址
	TxHash       string         `gorm:"column:tx_hash;comment:交易hash" json:"tx_hash"`             // 交易hash
	Status       string         `gorm:"column:status;comment:订单状态" json:"status"`                 // 订单状态
	NotifyStatus string         `gorm:"column:notify_status;comment:订单回调结果" json:"notify_status"` // 订单回调结果
	Remark       string         `gorm:"column:remark;comment:备注" json:"remark"`                   // 备注
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
