// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysWallet = "sys_wallet"

// SysWallet mapped from table <sys_wallet>
type SysWallet struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Ac           string         `gorm:"column:ac;not null;comment:钱包地址" json:"ac"`            // 钱包地址
	PriKey       string         `gorm:"column:pri_key;not null;comment:私钥" json:"pri_key"`    // 私钥
	Mnemonic     string         `gorm:"column:mnemonic;not null;comment:助记词" json:"mnemonic"` // 助记词
	Path         string         `gorm:"column:path;not null;comment:钱包路径" json:"path"`        // 钱包路径
	Remark       string         `gorm:"column:remark;comment:备注" json:"remark"`               // 备注
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CurrentIndex int32          `gorm:"column:current_index;not null;comment:当前派生索引" json:"current_index"` // 当前派生索引
	Version      int32          `gorm:"column:version;not null" json:"version"`
}

// TableName SysWallet's table name
func (*SysWallet) TableName() string {
	return TableNameSysWallet
}
